version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"   # Map container 3000 to host 4000 (avoid clash with frontend)
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"   # Next.js frontend exposed on host 3000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
